### ISSUE TITLE
Self-hosted Dapr on multiple machines. Is it possible?

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [markheath/globoticket-dapr#1]
I would like to run self-hosted services on different hosts. If it is possible please provide some example or link to documentation with details.  My Monolith is running on several physical machines but is not ready for migration to .NET core and as result I can't use Kubernetes. Single option for me is self-hosted dapr sidecars but I can't see if it is even possible.

**Comment by markheath** [comment]
Yes, this is perfectly possible, you'd just need to use an appropriate host name resolution component. The [default is mDNS](https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-mdns/), which I don't know if would work in your scenario, but you can [use HashiCorp Consul](https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/) instead

**Comment by AlexanderKapelyukhovskiy** [comment]
Thank you for links! I started learning docs about consul but sill don't have clear picture. Should I start consul server on some dedicated server and put in sidecars configuration (hostname and ip of that counsel server along with component: "consul")  ?

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "MyConsulServerHostNam:MyConsulServerPort"
```
